const activities=[{icon:'＋',tone:'blue',title:'Nova Esports がエントリーしました',detail:'SQUAD / チームチャンネルを作成',time:'2分前'},{icon:'◈',tone:'purple',title:'VC参加ロールを更新しました',detail:'@voice-active を対象VCに設定',time:'18分前'},{icon:'✓',tone:'green',title:'Pulse Gaming の認証が完了しました',detail:'代表者ロールを付与',time:'34分前'},{icon:'＋',tone:'blue',title:'Rift Walkers がエントリーしました',detail:'TRIO / チームチャンネルを作成',time:'1時間前'}];
const pageMeta={overview:['OVERVIEW','おかえりなさい、運営さん。','大会の受付状況とボットの状態を確認できます。'],entry:['ENTRY CONFIGURATION','エントリー設定','大会の受付ルールをサーバーごとに管理します。'],roles:['ROLE MANAGEMENT','ロール管理','エントリー時とVC参加時のロール付与をまとめて設定します。'],channels:['CHANNELS & TEAMS','チャンネル管理','ボットが作成した大会用チャンネルだけを安全に確認・削除できます。'],activity:['AUDIT LOG','アクティビティ','設定変更やチーム作成の履歴を確認できます。']};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function showToast(text){const toast=$('#toast');toast.textContent=text;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),2600)}
function renderActivities(){const markup=activities.map(a=>`<div class="activity-item"><span class="activity-icon ${a.tone}">${a.icon}</span><div><strong>${a.title}</strong><small>${a.detail}</small></div><span class="activity-time">${a.time}</span></div>`).join('');$('#activityList').innerHTML=markup;$('#activityTimeline').innerHTML=activities.map(a=>`<div class="timeline-entry"><span class="timeline-mark"></span><div><strong>${a.title}</strong><p>${a.detail}</p></div><time>${a.time}</time></div>`).join('')}
function setView(view){$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));$$('.content-wrap').forEach(s=>s.classList.add('hidden'));$(`#view-${view}`).classList.remove('hidden');const meta=pageMeta[view]||pageMeta.overview;$('#breadcrumbView').textContent=meta[0];$('#pageTitle').textContent=meta[1];$('#pageSubtitle').textContent=meta[2];window.scrollTo({top:0,behavior:'smooth'})}
function openReset(){ $('#resetModal').classList.remove('hidden') }function closeReset(){ $('#resetModal').classList.add('hidden') }
$$('.nav-item').forEach(n=>n.addEventListener('click',()=>setView(n.dataset.view)));$$('[data-jump]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.jump)));
$$('[data-action="reset"]').forEach(b=>b.addEventListener('click',openReset));$$('[data-action="vc"]').forEach(b=>b.addEventListener('click',()=>{setView('roles');showToast('VCロール設定を開きました')}));
$('#cancelReset').addEventListener('click',closeReset);$('#resetModal').addEventListener('click',e=>{if(e.target.id==='resetModal')closeReset()});$('#confirmReset').addEventListener('click',()=>{closeReset();showToast('このサーバーの設定を初期化しました');setTimeout(()=>setView('overview'),300)});
$('#refreshButton').addEventListener('click',()=>{showToast('最新の状態に同期しました');$('#refreshButton').textContent='✓　同期済み';setTimeout(()=>$('#refreshButton').textContent='↻　同期する',1800)});
$('#saveEntry').addEventListener('click',()=>showToast('エントリー設定を保存しました'));$('#saveRoles').addEventListener('click',()=>showToast('ロール設定を保存しました'));$('#deleteTeams').addEventListener('click',()=>showToast('安全確認後にVPS APIへ接続します'));$('#clearActivity').addEventListener('click',()=>{activities.length=0;renderActivities();showToast('アクティビティログをクリアしました')});
$('#entryToggle').addEventListener('change',e=>{const label=document.querySelector('#view-entry .view-heading .status-badge');label.textContent=e.target.checked?'受付中':'終了';label.classList.toggle('on',e.target.checked);showToast(e.target.checked?'エントリー受付を開始しました':'エントリー受付を終了しました')});
$$('.format-option input').forEach(input=>input.addEventListener('change',e=>e.target.closest('.format-option').classList.toggle('selected',e.target.checked)));
$$('.tag button').forEach(b=>b.addEventListener('click',()=>b.closest('.tag').remove()));$('#serverButton').addEventListener('click',()=>showToast('サーバー切り替えはDiscord OAuth2接続後に利用できます'));$('#userButton').addEventListener('click',()=>showToast('管理者アカウント'));window.addEventListener('keydown',e=>{if(e.key==='Escape')closeReset()});renderActivities();
window.EntryBotApi={baseUrl:'',token:'',configure({baseUrl,token}={}){this.baseUrl=baseUrl||'';this.token=token||''},async request(path,options={}){if(!this.baseUrl)throw new Error('API未接続');const res=await fetch(`${this.baseUrl}${path}`,{...options,headers:{'Content-Type':'application/json',...(this.token?{Authorization:`Bearer ${this.token}`}:{})}});if(!res.ok)throw new Error(`API ${res.status}`);return res.json()}};
